// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIuYSGrlJRZZ2kdEUQ89mp4wwbRBvJi4',
    appId: '1:377432360948:web:fce9f91ec8a91773c09ba1',
    messagingSenderId: '377432360948',
    projectId: 'presence-aa309',
    authDomain: 'presence-aa309.firebaseapp.com',
    storageBucket: 'presence-aa309.appspot.com',
    measurementId: 'G-17VZT2XVQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJaOCjKZeM9W_0J8soOsn4VHzm0rtvQhg',
    appId: '1:377432360948:android:0417e2cd402f6641c09ba1',
    messagingSenderId: '377432360948',
    projectId: 'presence-aa309',
    storageBucket: 'presence-aa309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEfyV_oCi0yFK1n75_BG9ZVn5Ap5e1mM',
    appId: '1:377432360948:ios:b47b5141995a27a3c09ba1',
    messagingSenderId: '377432360948',
    projectId: 'presence-aa309',
    storageBucket: 'presence-aa309.appspot.com',
    iosClientId: '377432360948-q4ohun1q201nnr3aapm50doaojq9e97u.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp',
  );
}
